name: 'Azure Terraform feature Ask' 
description: Request a feature for Azure Terraform Verified Modules, Examples, AzAPI provider, Azure Terrafy, etc.
title: "<title>"
labels: [enhancement]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: dropdown
  attributes:
    label: Where would you like this feature added?
    description: Let us know what product or area you would like to see this feature added to.
    multiple: false
    options:
      - "Verified Modules"
      - "AzAPI Provider"
      - "Azure Terrafy"
      - "Examples (Quickstart, Samples, etc.)"
      - "Other/Unknown"
  validations:
    required: true
- type: textarea
  attributes:
    label: Is this feature ask due to a problem that you are encountering?
    description: If so, please provide a clear and concise description of what the problem is.
    placeholder: I'm always frustrated when [...]
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe potential solutions.
    description: Please provide a clear and concise description of what you want to happen.
    placeholder: Add a way for me to [...]
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the feature you are requesting!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
