blank_issues_enabled: true
contact_links:
  - name: AzureRM provider issues and Feature requests
    url: https://github.com/hashicorp/terraform-provider-azurerm/issues
    about: Please ask questions and report issues with the AzureRM provider and related resources here. 
