kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-aks-user-ingress
  namespace: nginx-ingress
subjects:
# AKS User Group 
- kind: Group
  name: "2e9d53f9-f11e-46ec-a571-a0fd4809f602"
roleRef:
  kind: Role
  name: role-aks-user-ingress
  apiGroup: rbac.authorization.k8s.io
