apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: role-aks-user-ingress
  namespace: nginx-ingress
rules:
- apiGroups: [""]
  resources: ["ingresses","services"]
  verbs: ["get", "watch", "list"]
